### ISSUE TITLE
yarn install is failing

### ISSUE THREAD

**Issue by tolulawson** [enesozturk/react-native-ios#2]
`error` An unexpected error occurred: "https://registry.yarnpkg.com/colors/-/colors-1.4.1.tgz: Request failed \"404 Not Found\"".

**Comment by farzin-deriv** [comment]
@tolulawson Just delete the existing `yarn.lock` file and run `yarn install` again.

**Comment by andresribeiro** [comment]
@farzin-fs thanks, it worked for me

**Comment by enesozturk** [comment]
Great, thanks guys!
